registry_vals = [
    ('NoUpdateCheck', 1, 4),
    ('NoJITSetup', 1, 4),
    ('Disable Script Debugger', u'yes', 1),
    ('Show_ChannelBand', u'No', 1),
    ('Anchor Underline', u'yes', 1),
    ('Cache_Update_Frequency', u'Once_Per_Session', 1),
    ('Display Inline Images', u'yes', 1),
    ('Do404Search', '\x01\x00\x00\x00', 3),
    ('Local Page', u'C:\\WINDOWS\\system32\\blank.htm', 1),
    ('Save_Session_History_On_Exit', u'no', 1),
    ('Show_FullURL', u'no', 1),
    ('Show_StatusBar', u'yes', 1),
    ('Show_ToolBar', u'yes', 1),
    ('Show_URLinStatusBar', u'yes', 1),
    ('Show_URLToolBar', u'yes', 1),
    ('Start Page', u'about:blank', 1),
    ('Use_DlgBox_Colors', u'yes', 1),
    ('Search Page', u'http://www.microsoft.com/isapi/redir.dll?prd=ie&ar=iesearch', 1),
    ('Check_Associations', u'No', 1),
    ('Error Dlg Displayed On Every Error', u'no', 1),
    ('FullScreen', u'no', 1),
    ('NotifyDownloadComplete', u'yes', 1),
    ('Error Dlg Details Pane Open', u'no', 1),
    ('Window_Placement', ',\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00 \x03\x00\x00:\x02\x00\x00', 3),
    ('ShowedCheckBrowser', u'Yes', 1),
    ('XMLHTTP', 1, 4),
    ('UseClearType', u'yes', 1),
    ('Enable Browser Extensions', u'yes', 1),
    ('Play_Background_Sounds', u'yes', 1),
    ('Play_Animations', u'yes', 1),
    ('CompatibilityFlags', 0, 4),
    ('IE8RunOnceLastShown', 1, 4),
    ('IE8RunOnceLastShown_TIMESTAMP', '\xb8\x95\x1e\x13\xb5\xe9\xcb\x01', 3),
    ('IE8RunOncePerInstallCompleted', 1, 4),
    ('IE8RunOnceCompletionTime', '\xc8\xdf\xde4\xb5\xe9\xcb\x01', 3),
    ('IE8TourShown', 1, 4),
    ('IE8TourShownTime', '\xc8\xdf\xde4\xb5\xe9\xcb\x01', 3),
]
